[bumpver]
current_version = "3.1.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit = true
push = true
tag = true

[bumpver.file_patterns]
"setup.py" = [
    'version="{version}"',
]

"bumpver.toml" = [
    'current_version = "{version}"'
]