name: Publish to Twine by getting version from Github pull request description and using bumpver to bump version and publish

on:
  pull_request:
    types: [ closed ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Bump and Publisher Distribution to PyPi
        uses: YousefEZ/auto-pypi@0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          twine-token: ${{ secrets.TWINE_USERNAME }}
          
